  name: FrostGuard
  version: 1.2
  main: org.tahoma.frostguards.FrostGuard
  api-version: 1.16
  author: Tahoma34
  description: Плагин для заморозки игроков и модерации

  commands:
    fg:
      description: Команда управления плагином FrostGuard
      usage: /fg <freeze|radius|reload|unfreeze|unfreezeall|list|check> ...
      permission: frostguard.freeze
      aliases: [frostg, frostguard]

  permissions:
    frostguard.freeze:
      description: Позволяет замораживать игроков
      default: op
    frostguard.radius:
      description: Позволяет замораживать игроков в радиусе
      default: op
    frostguard.reload:
      description: Позволяет перезагружать настройки плагина
      default: op
    frostguard.unfreeze:
      description: Позволяет размораживать конкретных игроков
      default: op
    frostguard.unfreezeall:
      description: Позволяет размораживать всех игроков
      default: op
    frostguard.list:
      description: Позволяет смотреть список замороженных игроков
      default: op
    frostguard.check:
      description: Позволяет проверять состояние заморозки у игроков
      default: op
